# Generated by Django 5.1.7 on 2025-03-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='User',
        ),
    ]
